version: '2'
services:
  server:
    image: gilleswittenberg/treey.io-server:development
    container_name: treey.io-server
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - '8081:8081'
  mongo:
    image: mongo:2
    container_name: treey.io-mongo
    volumes:
      - ./docker-compose/mongo/data/db:/data/db
      - ./docker-compose/mongo/data/configdb:/data/configdb
    ports:
      - '27017:27017'
